Style/Documentation:
  Enabled: false

Security/Eval:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Metrics/ClassLength:
  Enabled: true
  Exclude: 
    - ./main.rb

Metrics/AbcSize:
  Enabled: true
  Exclude: 
    - ./main.rb
  IgnoredMethods:
    - attr_accessor_with_history
    - demonstrate

Metrics/CyclomaticComplexity:
  Enabled: true
  Exclude: 
    - ./main.rb

Metrics/MethodLength:
  Enabled: true
  Max: 15
  Exclude: 
    - ./main.rb

Metrics/BlockLength:
  Enabled: true
  Exclude: 
    - ./main.rb

Style/ClassVars:
  Enabled: true
  Exclude: 
    - ./train.rb
    - ./station.rb